spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: expense-service
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expenses/**
          filters:
            - StripPrefix=1
            - JwtFilter
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**
          filters:
            - StripPrefix=1
            - JwtFilter
server:
  port: 8080
